// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://haodastqykbgflafrlfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhhb2Rhc3RxeWtiZ2ZsYWZybGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyOTUyNjUsImV4cCI6MjA1MDg3MTI2NX0.C61uN26D75rf_rA7x1INOQLIVm4X2GidC8DtREWy6eY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);